### ISSUE TITLE
Crash[Bug] 

### ISSUE THREAD

**Issue by godpow** [slow/nitro-sniper#132]
021-06-11T02:51:12.806729+00:00 app[worker.1]: /app/node_modules/discord.js-light/actions.js:331
2021-06-11T02:51:12.806739+00:00 app[worker.1]: 		const message = channel.messages.add(data, c.channels.cache.has(channel.id));
2021-06-11T02:51:12.806740+00:00 app[worker.1]: 		                                 ^
2021-06-11T02:51:12.806741+00:00 app[worker.1]: 
2021-06-11T02:51:12.806741+00:00 app[worker.1]: TypeError: Cannot read property 'add' of undefined
2021-06-11T02:51:12.806743+00:00 app[worker.1]:     at MessageCreateAction.client.actions.MessageCreate.handle (/app/node_modules/discord.js-light/actions.js:331:36)
2021-06-11T02:51:12.806743+00:00 app[worker.1]:     at Object.PacketHandlers.MESSAGE_CREATE (/app/node_modules/discord.js-light/handlers.js:185:51)
2021-06-11T02:51:12.806744+00:00 app[worker.1]:     at WebSocketManager.client.ws.handlePacket (/app/node_modules/discord.js-light/actions.js:38:28)
2021-06-11T02:51:12.806744+00:00 app[worker.1]:     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:442:22)
2021-06-11T02:51:12.806745+00:00 app[worker.1]:     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:299:10)
2021-06-11T02:51:12.806745+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16)
2021-06-11T02:51:12.806745+00:00 app[worker.1]:     at WebSocket.emit (events.js:376:20)
2021-06-11T02:51:12.806746+00:00 app[worker.1]:     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:835:20)
2021-06-11T02:51:12.806747+00:00 app[worker.1]:     at Receiver.emit (events.js:376:20)
2021-06-11T02:51:12.806747+00:00 app[worker.1]:     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:428:14)

**Comment by godpow** [comment]
just running like normal than that happened.

**Comment by godpow** [comment]
![image](https://user-images.githubusercontent.com/17231911/121626962-7554a300-ca44-11eb-82eb-084ece91d64b.png)

**Comment by slow** [comment]
i attempted a fix in the latest commit, re-open an issue if it happens again
