### ISSUE TITLE
Crash Heroku

### ISSUE THREAD

**Issue by NotVinnny** [slow/nitro-sniper#146]
**Not sure if it's happening just to me but:**

2021-06-25T23:11:45.395570+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'content' of undefined
2021-06-25T23:11:45.395580+00:00 app[worker.1]:     at Sniper.<anonymous> (/app/src/modules/Nitro.js:29:26)
2021-06-25T23:11:45.395581+00:00 app[worker.1]:     at Sniper.emit (events.js:375:28)
2021-06-25T23:11:45.395582+00:00 app[worker.1]:     at Object.PacketHandlers.MESSAGE_CREATE (/app/node_modules/discord.js-light/handlers.js:186:9)
2021-06-25T23:11:45.395582+00:00 app[worker.1]:     at WebSocketManager.client.ws.handlePacket (/app/node_modules/discord.js-light/actions.js:38:34)
2021-06-25T23:11:45.395582+00:00 app[worker.1]:     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:442:22)
2021-06-25T23:11:45.395583+00:00 app[worker.1]:     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:299:10)
2021-06-25T23:11:45.395583+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16)
2021-06-25T23:11:45.395584+00:00 app[worker.1]:     at WebSocket.emit (events.js:375:28)
2021-06-25T23:11:45.395584+00:00 app[worker.1]:     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:834:20)
2021-06-25T23:11:45.395585+00:00 app[worker.1]:     at Receiver.emit (events.js:375:28)
2021-06-25T23:11:45.395644+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)

**Comment by NotVinnny** [comment]
Issue has stopped
