### ISSUE TITLE
Fails to run on a vm with simple nodejs envoriment

### ISSUE THREAD

**Issue by MathiasTopKek** [slow/nitro-sniper#17]
root@instance-1:~/nitro-sniper# node .
/root/nitro-sniper/src/index.js:127
   if (!res.body || res.body?.length === 0) {
                             ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by slow** [comment]
Node version 14.0.0 or above is required as shown in the package.json.

**Comment by MathiasTopKek** [comment]
Worked i didn't even see that, my bad.
