### ISSUE TITLE
Nitro Sniper crashes

### ISSUE THREAD

**Issue by PhilZoockt** [slow/nitro-sniper#189]
Im getting this big error:
/root/NitroSniperBackup/src/modules/Nitro.js:29
         let codes = msg.content.match(this.regex.gift);
                         ^

TypeError: Cannot read property 'content' of undefined
    at Sniper.<anonymous> (/root/NitroSniperBackup/src/modules/Nitro.js:29:26)
    at Sniper.emit (node:events:394:28)
    at Object.PacketHandlers.MESSAGE_CREATE (/root/NitroSniperBackup/node_modules/discord.js-light/handlers.js:186:9)
    at WebSocketManager.client.ws.handlePacket (/root/NitroSniperBackup/node_modules/discord.js-light/actions.js:38:34)
    at WebSocketShard.onPacket (/root/NitroSniperBackup/node_modules/discord.js/src/client/websocket/WebSocketShard.js:442:22)
    at WebSocketShard.onMessage (/root/NitroSniperBackup/node_modules/discord.js/src/client/websocket/WebSocketShard.js:299:10)
    at WebSocket.onMessage (/root/NitroSniperBackup/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/root/NitroSniperBackup/node_modules/ws/lib/websocket.js:834:20)
    at Receiver.emit (node:events:394:28)

**Comment by slow** [comment]
This was already fixed in 0dc84a1d6ec775a6f13f50a280346f7b648bbee6. If you require more support join https://discord.gg/shnvz5ryAt
