### ISSUE TITLE
I am getting a wierd error on replit

### ISSUE THREAD

**Issue by Raffir2005** [slow/nitro-sniper#218]
Hello so i am getting a wierd error i have not gotton before on and wasnted to ask for some help.
 npx node .
/home/runner/nitro-sniper-1/src/index.js:86
   if (!res.body?.length) {
                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
exit status 1

This is the Error I get and wanted to ask if someone knows what i can do about this.
Thank you in advance.

**Comment by Deastt** [comment]
check your token make sure its like 
main: "yourtoken",

**Comment by slow** [comment]
Follow the issue template.
