### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ShamailNasir** [slow/nitro-sniper#229]
**Describe the bug**
I keep getting this error ,
w(node:690) UnhandledPromiseRejectionWarning: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:628:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1569:19)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:690) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by slow** [comment]
Duplicate of #216

**Comment by AryaAnish121** [comment]
You guys use github just for nitro-sniper?

**Comment by ShamailNasir** [comment]
> You guys use github just for nitro-sniper?

Yeah

**Comment by AryaAnish121** [comment]
> > You guys use github just for nitro-sniper?
> 
> Yeah, I don't even know if its legit

It's light but github is a place for sharing code
