### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by godpow** [slow/nitro-sniper#266]
### Describe the bug

Not sure it was working fine then I checked it then it crashed

It seems like deleting the the folder then rerunning the bash script fixed it.

### To Reproduce

Not sure it was working fine then I checked it then it crashed

### Expected behavior

It was working fine

### Please provide your snipers settings.

...

### What platform are you seeing the problem on?

Repl.it

### Relevant log output if applicable.

```shell
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- /home/runner/Snipe/nitro-sniper/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/Snipe/nitro-sniper/src/index.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/Snipe/nitro-sniper/src/index.js' ]
}
exit status 1
```

**Comment by slow** [comment]
It's almost like the errors tells you the issue.

Run `npm install` in the sniper folder.
